spec:
  replicas: 1
  template:
    spec:
      containers:
        - volumeMounts:
            - name: application-config
              mountPath: "/deployments/config"
              readOnly: true
          env:
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: deposits-transactions-db
                  key: database-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deposits-transactions-db
                  key: database-password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
      volumes:
        - name: application-config
          configMap:
            name: bs-${project.artifactId}
            items:
            - key: application.properties
              path: application.properties
